version: '3.9'
services:
  train:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    image: easy-lora-train
    container_name: easy-lora-train
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
  download_images:
    image: easy-lora-train
    container_name: download_images
    volumes:
      - .:/workspace
    entrypoint:
      - ./download_images.sh
    stdin_open: true
    tty: true
